server:
  port: 8894
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8
spring:
  application:
    name: saa07-RAG
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3-max  # 指定文本模型
      embedding:
        options:
          model: qwen3.7-text-embedding  # 指定向量化模型
    vectorstore:
      milvus:
        client:
          host: 192.168.12.177
          port: 19530
          token: root:Milvus
        database-name: default
        collection-name: guide_store
        initialize-schema: true
        embedding-dimension: 1024

logging:
  pattern:
    console: "%-5level %logger - %msg%n" # 设置日志格式